clear; clc;close all;
num = 1;
den = [0.5, 1];
sys = tf(num,den);
t1 = 0:0.01:3;
[y, t1] = step(sys,t1);
figure,step(sys,t1)
figure,plot(t1,y);
n = length(t1);
n1 = abs(y-y(n))/y(n) > 0.05;
n2 = sum(n1);
N = 10;
T = n2*0.01/N;
delta = linspace(2,n2,N);
delta = floor(delta);
S = y(delta);
figure, plot(S);
I = eye(N);
Mss = zeros(1,N);
Mss(end) = 1;
Mss = [I;Mss];
Mss(1,:) = [];
Yk_1 = zeros(N,1);
Yk = zeros(N,1);
yk(1) = 0; yk(2) = 0;
t = 0:T:8;
u = sin(t);
for i = 3:length(u);
    Yk = Mss*Yk_1 + S*(u(i-1)-u(i-2));
    yk(i) = Yk(1);
    Yk_1 = Yk;
end
figure, plot(t,yk,'r.-'); hold on;
[yy,t] = lsim(sys,u,t);
plot(t,yy,'b--');plot(t,u,'k');
legend( '模型输出', '实际输出','输入信号');